---
name: Tests

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - '*'          # matches every branch that doesn't contain a '/'
      - '*/*'        # matches every branch containing a single '/'
      - '**'         # matches every branch
      - '!gh-pages'  # excludes gh-pages
  pull_request:
    types: [opened]
jobs:
  Tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: make install
      - name: Test linters
        run: make lint
      - name: Test type checkers
        run: make mypy
      - name: Test security
        run: make security
      - name: Test with pytest
        run: make test
      - name: Upload Coverage
        run: |
          pip3 install coveralls
          coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_FLAG_NAME: ${{ matrix.test-name }}
          COVERALLS_PARALLEL: true
      - name: Test documentation
        run: make build-docs
  Coveralls:
    name: Finish Coveralls
    needs: Tests
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
      - name: Finished
        run: |
          pip3 install coveralls
          coveralls --service=github --finish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  Python_Package:
    name: Build the Python package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install PEP517
        run: >-
          python -m
          pip install
          pep517
          --user
      - name: Build a binary wheel and a source tarball
        run: >-
          python -m
          pep517.build
          --source
          --binary
          --out-dir dist/
          .
